DATA:
  dataset: vox
  data_root: ./VoxCeleb
  read_audio: False


NETWORK:
  arch: flame
  in_dim: 15069
  hidden_size: 1024
  num_hidden_layers: 6
  num_attention_heads: 8
  intermediate_size: 1536
  window_size: 1
  neg: 0.2
  INaffine: False


TRAIN:
  use_sgd: False
  train_gpu: 0
  workers: 10  # data loader workers
  batch_size: 1  # batch size for training
  batch_size_val: 1  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.0001
  StepLR: True
  warmup_steps: 1
  adaptive_lr: False
  factor: 0.3
  patience: 3
  threshold: 0.0001
  epochs: 200
  step_size: 20
  gamma: 0.5
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.002
  manual_seed: 131
  print_freq: 10
  save_freq: 1
  save_path:
#  weight: 
  weight:
  resume:
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 5
  visualize: False
  visualize_freq: 10

